### ISSUE TITLE
Workplan @August 2021

### ISSUE THREAD

**Issue by AdeBC** [AdeBC/AdeBC#1]
## Week 31 (1-6 Aug)
- [ ] Finish graph construction for environments with few samples (e.g., dog gut, cat gut, wastewater) **#GlobalSynteny**
- [ ] Annotate the graph, is there any possible novel finding? **#GlobalSynteny**
- [ ] AMP card design **#AMPSphereWebsite**
- [ ] Family card design (beginning) **#AMPSphereWebsite**
- [ ] Start finalizing EXPERT manuscript  **#EXPERT**

## Week 32 (8-13 Aug)
- [ ] Read some relevant paper and think about potential directions **#GlobalSynteny**
- [ ] Finish graph construction for more environments **#GlobalSynteny**
- [ ] Family card design **#AMPSphereWebsite**
- [ ] Home page updates (show environment selector, examples or microontology) **#AMPSphereWebsite**
- [ ] Finalizing EXPERT manuscript **#EXPERT**
- [ ] Language editing **#EXPERT**

## Week 33 (15-20 Aug)
- [ ] Directions for GlobalSynteny? **#GlobalSynteny**
- [ ] Finish graph construction for all environments **#GlobalSynteny**
- [ ] Design data exchange API for backend and frontend **#AMPSphereWebsite**
- [ ] Finalize frontend version 0.1 developing **#AMPSphereWebsite**

## Week 34 (22-26 Aug)
- [ ] Directions for GlobalSynteny? **#GlobalSynteny**
- [ ] Backend framework design **#AMPSphereWebsite** 
- [ ] Backend API implementation and Schema developing **#AMPSphereWebsite** 
- [ ] Start database mapping logics & database design **#AMPSphereWebsite** 
- [ ] Manuscript final check **#EXPERT**
